### ISSUE TITLE
Hanweir Battlements and BRO cards not recognized

### ISSUE THREAD

**Issue by ZarakiKanzaki** [Takeno/magic-events-gg#21]
Hi,

I wanted to report that the API used to fetch cards don't recognize Hanweir Battlements and BRO cards like Haywire Mite.

This prevents you from posting your decklist for an Event

Here are 2 screenshots

![immagine](https://user-images.githubusercontent.com/19550424/201920838-c20df5fb-fc14-47c0-ae4d-20051b409d31.png)

![immagine](https://user-images.githubusercontent.com/19550424/201921517-284e65fb-e3fd-4ebf-b2c5-107f83ba9c31.png)

**Comment by Takeno** [comment]
Hi @ZarakiKanzaki,
We've fixed the bug and also implemented a new way to manage decklists.

For any other issues, you can report them on appropriate repository here: https://github.com/Takeno/decklist-collector


Thanks for you time!

**Comment by ZarakiKanzaki** [comment]
Thank you very much for the information. I hope to help in the future ☺️
